### ISSUE TITLE
Enable emoji support

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#210]
### Describe the proposed change(s).

Material for MkDocs supports emoji's [^docs], but we need to enable some extensions first.

**Todo:**

- [x] Enable relevant extensions
- [x] Preview site locally, confirm it works
- [x] Check other things keep working
- [x] Open PR

[^docs]: [Material for MkDocs manual, icons/emojis](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/)
