### ISSUE TITLE
Enable image captions

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#211]
### Describe the proposed change(s).

Material for MkDocs supports "image captions". [^docs] When you use a image caption, the text for the image is centered below the image. This looks nicer than what we have now.

Example of using image captions:

```html
<figure markdown>
  ![Image title](https://dummyimage.com/600x400/){ width="300" }
  <figcaption>Image caption</figcaption>
</figure>
```

To actually use the captions, we need to edit our Markdown files in the main `renovatebot/renovate` repository.

**Todo:**

- [x] enable the relevant extensions
- [x] override the `docs/` file manually in the local preview
- [x] run `make serve`
- [x] check if it displays properly
- [x] check if other things keep working 
- [x] open PR on docs site to enable the feature
- [x] open PR on `renovatebot/renovate` to fix the Swissquote article and the articles in "Deep dives" with images

[^docs]: [Material for MkDocs manual, images](https://squidfunk.github.io/mkdocs-material/reference/images/)
