### ISSUE TITLE
Replace hooks plugin with native MkDocs 1.4.0 `hooks:` config

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#229]
## Intro

MkDocs 1.4.0 [^mkdocs] has a new `hooks:` [^hooks] config option, which can load in Python scripts. This means we may be able to drop a dependency.

Material for MkDocs does not support this new `hooks:` config option (yet). I opened an issue to ask for the `hooks:` option to be supported, see the todo list below.

## Todo:

- [x] Wait for the update for `mkdocs` `1.4.0` to land in our repository
- [x] Wait until we get a version of Material for MkDocs that supports the `hooks:` feature:
  - [x] https://github.com/squidfunk/mkdocs-material/issues/4420
- [x] Drop `mkdocs-simple-hooks` dependency from our `Pipfile`, drop lockfile
- [x] Run `pipenv install` to get a fresh lockfile
- [x] Drop the `mkdocs-simple-hooks` lines from the `mkdocs.yml` file
- [x] Update `mkdocs.yml` so it uses the new `hooks:` option
- [x] Run build, test if things keep working

### Python script

https://github.com/renovatebot/renovatebot.github.io/blob/8b6e6ae7a0848d90a92ed73c286598b1cc5637b9/mkdocs-hooks/custom-edit-url.py#L1-L6

### Stuff to drop during refactor

https://github.com/renovatebot/renovatebot.github.io/blob/8b6e6ae7a0848d90a92ed73c286598b1cc5637b9/mkdocs.yml#L158-L160

https://github.com/renovatebot/renovatebot.github.io/blob/8b6e6ae7a0848d90a92ed73c286598b1cc5637b9/Pipfile#L10

[^mkdocs]: https://github.com/mkdocs/mkdocs/releases/tag/1.4.0
[^hooks]: https://www.mkdocs.org/user-guide/configuration/#hooks
